### PR TITLE
shuf supports the -n flag.  Use this instead of head

### PR DESCRIPTION
**Pull request by mtbentley**

### CODE REVIEW

**Comment by ajm188** [comment]
:+1: RIP @brenns10

**Comment by brenns10** [comment]
I suppose I just prefer the Unix philosophy of small tools that do one thing well.

**Comment by ajm188** [comment]
Shots fired

**Comment by brenns10** [comment]
¯\_(ツ)_/¯

**Comment by mtbentley** [comment]
This change makes this tool smaller and better.

**Pull request merged**
